Projects/web app/Chapter 18:19:20 Blog app/code/urls.py
from django.urls import path
from .import views

app_name = 'blogs'
urlpatterns = [
    # Homepage
    path('', views.index, name='index'),
    # Posts
    path('posts/', views.posts, name='posts'),
    # View a single post
    path('post/<int:post_id>/', views.post, name="post"),
    # Creating new post
    path('new_post/', views.new_post, name='new_post'),
    # Edit post
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

Projects/web app/Chapter 18:19:20 Blog app/code/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class BlogPost(models.Model):
    """Creating blog topics and text"""
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Retunrning title"""
        return self.title

Projects/web app/Chapter 18:19:20 Blog app/code/forms.py
from django import forms
from .models import BlogPost

class PostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ('title', 'text')

Projects/web app/Chapter 18:19:20 Blog app/code/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, redirect, get_object_or_404
from .models import BlogPost
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
def index(request):
    """Homepage for blogs"""
    return render(request, 'blogs/index.html')

@login_required
def posts(request):
    """Shows the blogposts list"""
    posts = BlogPost.objects.order_by('date_added')
    context = {'posts': posts}
    return render(request, 'blogs/posts.html', context)

@login_required
def post(request, post_id):
    """Show a single blog post."""
    post = get_object_or_404(BlogPost, id=post_id)
    title = post.title
    text = post.text
    date = post.date_added
    owner = post.owner
    context = {'title': title, 'text': text, 'date': date, 'owner': owner}
    return render(request, 'blogs/post.html', context)

@login_required
def new_post(request):
    """Creating new topic"""
    if request.method != 'POST':
        #Data didn't sent; create empty form
        form = PostForm()
    else:
        # Data sent POST; process data
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect('blogs:posts')

    # Show empty or invalid form
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, post_id):
    """Edit post"""
    post = get_object_or_404(BlogPost, id=post_id)
    check_post_owner(post.owner, request)
    
    if request.method != 'POST':
        # Request; form is filled with the data from current post
        form = PostForm(instance=post)

    else:
        # Sending POST data; process data
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:post', post_id=post.id)

    context = {'post': post, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

def check_post_owner(owner, request):
    if owner != request.user:
        raise Http404

Projects/web app/Chapter 18:19:20 Blog app/code/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>Blog</title> 

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'blogs:index'%}">
        Blog</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blogs:posts'%}">
              Posts</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text"}">Hello, {{ user.username }}.</span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
          {% endif %}
        </ul>
      </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div> 
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>




    

Projects/web app/Chapter 18:19:20 Blog app/code/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>
  <h4>Edit post:</h4>
  </h2>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'blogs:edit_post' post.id %}"method='post', class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit", class="btn btn-primary">Save changes</button>
    {% endbuttons %}
  </form>


{% endblock content %}

Projects/web app/Chapter 18:19:20 Blog app/code/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Post your nonsense.</h1>
    
    <p class="lead">Very Pog Blog website for your blog posts!</p>
    {% if not user.is_authenticated %}
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;</a>
    {% endif %}
  </div>
{% endblock page_header %}

Projects/web app/Chapter 18:19:20 Blog app/code/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>Add a new post:</h2>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'blogs:new_post' %}" method='post', class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit", class="btn btn-primary">Add post</button>
    {% endbuttons %}
  </form>


{% endblock content %}

Projects/web app/Chapter 18:19:20 Blog app/code/templates/blogs/post.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <h2>{{ title }}</h2>
{% endblock page_header %}

{% block content %}
  
  <pre><h5>{{ text }}</h5></pre>
  
  <p>Created: {{ date }}</p>

  <p>Created by: {{ owner }}</p>

{% endblock content %}

Projects/web app/Chapter 18:19:20 Blog app/code/templates/blogs/posts.html
{% extends "blogs/base.html" %}

{% block page_header %} 
  <h1>Blog posts</h1>
{% endblock page_header %}

{% block content %}
  <ul>
    {% for post in posts %}
      <li><h3>
        <a href="{% url 'blogs:post' post.id %}">{{ post.title }}</a> 
        {% if request.user == post.owner %} 
          - <a href="{% url 'blogs:edit_post' post.id %}">Edit post</a>
        {% endif %}
      </h3></li>
    {% empty %}
      <li><h3>No posts have been created yet</h3></li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'blogs:new_post' %}">Add a new post:</a></h3>
{% endblock content %}